/* Generated by Yosys 0.50+56 (git sha1 176131b50, clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
(* src = "../src/decoder3_to_8.v:1.1-28.10" *)
module decoder3_to_8(in, out, en);
  (* src = "../src/decoder3_to_8.v:7.2-27.4" *)
  wire [7:0] _00_;
  wire [7:0] _01_;
  wire [7:0] _02_;
  (* src = "../src/decoder3_to_8.v:3.7-3.9" *)
  input en;
  wire en;
  (* src = "../src/decoder3_to_8.v:2.14-2.16" *)
  input [2:0] in;
  wire [2:0] in;
  (* src = "../src/decoder3_to_8.v:4.14-4.17" *)
  output [7:0] out;
  wire [7:0] out;
  assign _01_[7] = in[1] ? (* src = {0{1'b0}} *) 1'h0 : _02_[7];
  assign _01_[1] = in[1] ? (* src = {0{1'b0}} *) _02_[7] : 1'h0;
  assign _00_[1] = in[2] ? (* src = {0{1'b0}} *) 1'h0 : _01_[0];
  assign _00_[2] = in[2] ? (* src = {0{1'b0}} *) 1'h0 : _01_[1];
  assign _00_[3] = in[2] ? (* src = {0{1'b0}} *) 1'h0 : _01_[2];
  assign _00_[4] = in[2] ? (* src = {0{1'b0}} *) _01_[7] : 1'h0;
  assign _00_[5] = in[2] ? (* src = {0{1'b0}} *) _01_[0] : 1'h0;
  assign _00_[6] = in[2] ? (* src = {0{1'b0}} *) _01_[1] : 1'h0;
  assign _00_[7] = in[2] ? (* src = {0{1'b0}} *) _01_[2] : 1'h0;
  assign _00_[0] = in[2] ? (* src = {0{1'b0}} *) 1'h0 : _01_[7];
  assign _01_[0] = in[1] ? (* src = {0{1'b0}} *) 1'h0 : in[0];
  assign _01_[2] = in[1] ? (* src = {0{1'b0}} *) in[0] : 1'h0;
  assign out[0] = en ? (* src = "../src/decoder3_to_8.v:10.11-10.13|../src/decoder3_to_8.v:10.7-26.10" *) _00_[0] : 1'h0;
  assign out[1] = en ? (* src = "../src/decoder3_to_8.v:10.11-10.13|../src/decoder3_to_8.v:10.7-26.10" *) _00_[1] : 1'h0;
  assign out[2] = en ? (* src = "../src/decoder3_to_8.v:10.11-10.13|../src/decoder3_to_8.v:10.7-26.10" *) _00_[2] : 1'h0;
  assign out[3] = en ? (* src = "../src/decoder3_to_8.v:10.11-10.13|../src/decoder3_to_8.v:10.7-26.10" *) _00_[3] : 1'h0;
  assign out[4] = en ? (* src = "../src/decoder3_to_8.v:10.11-10.13|../src/decoder3_to_8.v:10.7-26.10" *) _00_[4] : 1'h0;
  assign out[5] = en ? (* src = "../src/decoder3_to_8.v:10.11-10.13|../src/decoder3_to_8.v:10.7-26.10" *) _00_[5] : 1'h0;
  assign out[6] = en ? (* src = "../src/decoder3_to_8.v:10.11-10.13|../src/decoder3_to_8.v:10.7-26.10" *) _00_[6] : 1'h0;
  assign out[7] = en ? (* src = "../src/decoder3_to_8.v:10.11-10.13|../src/decoder3_to_8.v:10.7-26.10" *) _00_[7] : 1'h0;
  assign _02_[7] = ~(* src = {0{1'b0}} *) in[0];
  assign _01_[6:3] = 4'h0;
  assign _02_[6:0] = { 6'h00, in[0] };
endmodule
