/* Generated by Yosys 0.50+56 (git sha1 176131b50, clang++ 18.1.3 -fPIC -O3) */

module decoder3_to_8(in, out, en);
  input en;
  wire en;
  input [2:0] in;
  wire [2:0] in;
  output [7:0] out;
  wire [7:0] out;
  sky130_fd_sc_hd__nor4b_1 _0_ (
    .A(in[1]),
    .B(in[2]),
    .C(in[0]),
    .D_N(en),
    .Y(out[0])
  );
  sky130_fd_sc_hd__nor4bb_1 _1_ (
    .A(in[1]),
    .B(in[2]),
    .C_N(in[0]),
    .D_N(en),
    .Y(out[1])
  );
  sky130_fd_sc_hd__nor4bb_1 _2_ (
    .A(in[2]),
    .B(in[0]),
    .C_N(en),
    .D_N(in[1]),
    .Y(out[2])
  );
  sky130_fd_sc_hd__and4b_1 _3_ (
    .A_N(in[2]),
    .B(in[0]),
    .C(en),
    .D(in[1]),
    .X(out[3])
  );
  sky130_fd_sc_hd__nor4bb_1 _4_ (
    .A(in[1]),
    .B(in[0]),
    .C_N(en),
    .D_N(in[2]),
    .Y(out[4])
  );
  sky130_fd_sc_hd__and4b_1 _5_ (
    .A_N(in[1]),
    .B(in[2]),
    .C(in[0]),
    .D(en),
    .X(out[5])
  );
  sky130_fd_sc_hd__and4b_1 _6_ (
    .A_N(in[0]),
    .B(en),
    .C(in[1]),
    .D(in[2]),
    .X(out[6])
  );
  sky130_fd_sc_hd__and4_1 _7_ (
    .A(in[1]),
    .B(in[2]),
    .C(in[0]),
    .D(en),
    .X(out[7])
  );
endmodule
